USE [master]
GO
/****** Object:  Database [jdbc]    Script Date: 24/01/2022 10:33:03 CH ******/
CREATE DATABASE [jdbc]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'jdbc', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\jdbc.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'jdbc_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\jdbc_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [jdbc] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [jdbc].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [jdbc] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [jdbc] SET ANSI_NULLS OFF
GO
ALTER DATABASE [jdbc] SET ANSI_PADDING OFF
GO
ALTER DATABASE [jdbc] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [jdbc] SET ARITHABORT OFF
GO
ALTER DATABASE [jdbc] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [jdbc] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [jdbc] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [jdbc] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [jdbc] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [jdbc] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [jdbc] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [jdbc] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [jdbc] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [jdbc] SET  DISABLE_BROKER
GO
ALTER DATABASE [jdbc] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [jdbc] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [jdbc] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [jdbc] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [jdbc] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [jdbc] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [jdbc] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [jdbc] SET RECOVERY FULL
GO
ALTER DATABASE [jdbc] SET  MULTI_USER
GO
ALTER DATABASE [jdbc] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [jdbc] SET DB_CHAINING OFF
GO
ALTER DATABASE [jdbc] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [jdbc] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [jdbc] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [jdbc] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'jdbc', N'ON'
GO
ALTER DATABASE [jdbc] SET QUERY_STORE = OFF
GO
USE [jdbc]
GO
/****** Object:  Table [dbo].[Table_1]    Script Date: 24/01/2022 10:33:03 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Table_1](
	[id] [nchar](10) NULL,
	[name] [nchar](10) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Table_2]    Script Date: 24/01/2022 10:33:04 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Table_2](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [jdbc] SET  READ_WRITE
GO
